CREATE TABLE wishlists (
	id INTEGER PRIMARY KEY AUTOINCREMENT
);
CREATE TABLE wishlist_items (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	wishlist_id INT NOT NULL REFERENCES wishlists (id),
	item_name TEXT NOT NULL
);
